export const GAS_URL =
  'https://script.google.com/macros/s/AKfycbzOy8N1a_Ojfpa1IvMlJe5b3HHfrTCpjtECwWUXHijSA38MPJAAp4ZQLzJffIQTXcoc/exec';

export const RECAPTCHA_KEY = '6Lc2N6AsAAAAALHYvWU4qUdHoTlxC2lo0KY9oLBH';

export const bairrosSabara: string[] = [
  'Adelmolândia',
  'Água Férrea',
  'Alto do Cabral',
  'Alto do Fidalgo',
  'Alvorada',
  'Ana Lúcia',
  'Área Rural de Sabará',
  'Arraial Velho',
  'Borba Gato',
  'Borges',
  'Caieira',
  'Centro',
  'Conjunto Morada da Serra',
  'Córrego da Ilha',
  'Distrito Industrial Simão da Cunha',
  'Esplanada',
  'Fogo Apagou',
  'Itacolomi',
  'Jardim Castanheiras',
  'Mangabeiras',
  'Mangueiras',
  'Morro da Cruz',
  'Morro São Francisco',
  'Nações Unidas',
  'Nossa Senhora da Conceição',
  'Nossa Senhora de Fátima',
  'Nossa Senhora do Ó',
  'Novo Alvorada',
  'Novo Horizonte',
  'Novo Santa Inês',
  'Paciência',
  'Padre Chiquinho',
  'Pompeu',
  'Praia dos Bandeirantes',
  'Rio Negro',
  'Roça Grande',
  'Rosário',
  'Santana',
  'Santo Antônio (Roça Grande)',
  'São José',
  'Siderúrgica',
  'Sobradinho',
  'Terra Santa',
  'Valparaíso',
  'Vila Amélia Moreira',
  'Vila Bom Retiro',
  'Vila Campinas',
  'Vila dos Coqueiros',
  'Vila Esperança',
  'Vila Eugênio Rossi',
  'Vila Francisco de Moura',
  'Vila Marzagão',
  'Vila Michel',
  'Vila Nova Vista',
  'Vila Real',
  'Vila Rica',
  'Vila Santa Cruz',
  'Vila Santa Rita',
  'Vila Santo Antônio de Pádua',
  'Vila São Sebastião',
];
